/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/push/vapid-public-key": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Clé publique VAPID pour l'abonnement côté navigateur */
    get: operations["PushController_getVapidPublicKey"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/push/subscribe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Enregistre un abonnement Web Push et active le consentement notifications */
    post: operations["PushController_subscribe"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/push/unsubscribe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Supprime un abonnement Web Push et désactive le consentement notifications */
    post: operations["PushController_unsubscribe"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/notifications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Historique des notifications de l'utilisateur connecté */
    get: operations["NotifyController_getNotifications"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/notifications/unread-count": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Nombre de notifications non lues (dernières 24h) */
    get: operations["NotifyController_getUnreadCount"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness probe — le process tourne, sans dépendances */
    get: operations["HealthController_liveness"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness probe — vérifie Prisma/PostgreSQL */
    get: operations["HealthController_readiness"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/signup/owner": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Inscription propriétaire
     * @description Crée le compte Supabase Auth et le profil propriétaire, envoie l'email de confirmation WARAH.
     */
    post: operations["AuthController_signupOwner"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/signup/manager": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Inscription gestionnaire
     * @description Crée le compte Supabase Auth et le profil gestionnaire, envoie l'email de confirmation WARAH.
     */
    post: operations["AuthController_signupManager"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/invite/tenant": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Invite un locataire sur un bien
     * @description Réservé au propriétaire du bien ou au gestionnaire mandaté (canActOnProperty). Crée immédiatement le compte locataire (email confirmé d'office) et envoie le lien d'activation par email — le locataire n'aura plus qu'à poser un mot de passe.
     */
    post: operations["AuthController_inviteTenant"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/signup/tenant": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Active le compte locataire créé par l'invitation
     * @description Vérifie le token signé reçu par email (paramètre `token`, expire après 7 jours) et pose le mot de passe du compte déjà créé — aucun autre champ à fournir.
     */
    post: operations["AuthController_signupTenant"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Connexion par email et mot de passe
     * @description Route la connexion via NestJS (plutôt que directement Supabase côté client) pour appliquer le blocage de 15 minutes après 5 tentatives échouées. Renvoie une session Supabase valide en cas de succès.
     */
    post: operations["AuthController_login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Renouvelle la session avec le refresh token
     * @description Renvoie un nouveau access token et refresh token sans re-saisir le mot de passe.
     */
    post: operations["AuthController_refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/password-reset/request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Demande un code de réinitialisation de mot de passe
     * @description Envoie un code à 6 chiffres par email (expire après 10 minutes, usage unique). Toute nouvelle demande invalide les codes précédents. Réponse toujours générique, qu'un compte existe ou non pour cet email.
     */
    post: operations["AuthController_requestPasswordReset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/password-reset/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Confirme la réinitialisation avec le code reçu par email */
    post: operations["AuthController_confirmPasswordReset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Profil de l'utilisateur courant
     * @description Renvoie l'utilisateur courant avec son profil de rôle (Owner/Tenant/Manager/Admin), son statut de compte et ses préférences de notification.
     */
    get: operations["AuthController_me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/public/listings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Annonces publiques actives, paginées et filtrables
     * @description Aucune authentification requise. Alimentée automatiquement — jamais de publication manuelle.
     */
    get: operations["ListingsController_findAll"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/public/listings/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fiche détaillée d'une annonce (par slug) */
    get: operations["ListingsController_findOne"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Profil de l'utilisateur courant */
    get: operations["ProfileController_getProfile"];
    put?: never;
    post?: never;
    /**
     * Anonymise et désactive le compte
     * @description Supprime le compte Supabase Auth (connexion impossible ensuite) et vide les champs personnels côté Prisma (email, téléphone, nom). L'historique des paiements et baux est conservé pour les obligations légales.
     */
    delete: operations["ProfileController_anonymize"];
    options?: never;
    head?: never;
    /**
     * Met à jour les informations personnelles et/ou la photo de profil
     * @description Tous les champs sont optionnels (mise à jour partielle). La photo (`photo`) est compressée et convertie en WebP avant stockage.
     */
    patch: operations["ProfileController_updateProfile"];
    trace?: never;
  };
  "/profile/notification-consent": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Active ou désactive les notifications
     * @description Bascule uniquement la préférence — n'affecte pas les abonnements push déjà enregistrés sur les appareils (voir POST /push/subscribe, étape 06).
     */
    patch: operations["ProfileController_updateNotificationConsent"];
    trace?: never;
  };
  "/account/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Statut du compte courant — pour affichage du bandeau frontend */
    get: operations["AccountController_getStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/manager/owners/{ownerId}/report/preview.pdf": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Prévisualisation du rapport mensuel courant pour un propriétaire mandant
     * @description Couvre le mois civil en cours, avec les données disponibles jusqu'à maintenant — pas le dernier rapport déjà envoyé. Réservé au gestionnaire ayant au moins un mandat ACTIVE avec ce propriétaire.
     */
    get: operations["ManagerReportsController_preview"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/properties": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liste paginée des biens visibles par l'utilisateur courant */
    get: operations["PropertiesController_findAll"];
    put?: never;
    /** Enregistrer un nouveau bien — toujours VACANT, toujours l'appelant comme propriétaire */
    post: operations["PropertiesController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/properties/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Détail d'un bien, avec ses photos (URLs signées) */
    get: operations["PropertiesController_findOne"];
    put?: never;
    post?: never;
    /** Archiver un bien (jamais de suppression physique) */
    delete: operations["PropertiesController_remove"];
    options?: never;
    head?: never;
    /** Modifier la fiche ou le statut d'un bien */
    patch: operations["PropertiesController_update"];
    trace?: never;
  };
  "/properties/{id}/photos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ajoute jusqu'à 10 photos (plafond cumulatif) — compression WebP automatique */
    post: operations["PropertiesController_addPhotos"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/properties/{id}/photos/{photoId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Supprime une photo (Storage puis Prisma) */
    delete: operations["PropertiesController_removePhoto"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/properties/{id}/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liste les documents du bien avec URLs signées (15 min) */
    get: operations["PropertiesController_listDocuments"];
    put?: never;
    /** Ajoute des documents d'un même type (plafond cumulatif de 20) — jamais compressés */
    post: operations["PropertiesController_addDocuments"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/properties/{id}/documents/{documentId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Supprime un document (Storage puis Prisma) */
    delete: operations["PropertiesController_removeDocument"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/subscription/quota": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** État actuel du quota de biens facturables vs limite du forfait courant */
    get: operations["SubscriptionsController_getQuota"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/subscription/upgrade": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Migration instantanée vers un forfait supérieur, sans frais ni pénalité */
    post: operations["SubscriptionsController_upgrade"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/subscription/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Annulation — effective à la fin de la période payée */
    post: operations["SubscriptionsController_cancel"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/properties/{propertyId}/tenants/{tenantUserId}/block": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Bloque un locataire pour ce bien précis (justification obligatoire) */
    post: operations["PropertyTenantsController_blockTenant"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/properties/{propertyId}/tenants/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Historique des baux (passés et présent) de ce bien */
    get: operations["PropertyTenantsController_getHistory"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tenants": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liste les locataires invités par le propriétaire/gestionnaire courant */
    get: operations["TenantsController_listTenants"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tenants/{tenantUserId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Détail d'un locataire invité par le propriétaire/gestionnaire courant */
    get: operations["TenantsController_getTenant"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tenants/{tenantUserId}/leases/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Historique complet des baux passés et présent d'un locataire */
    get: operations["TenantsController_getLeasesHistory"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leases/{id}/terminate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Résilie un bail — libère le bien (VACANT), historique conservé */
    post: operations["LeasesController_terminate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leases/{id}/schedule": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Calendrier complet des échéances d'un bail */
    get: operations["LeasesController_getSchedule"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/payments/manual": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Enregistre un paiement reçu hors plateforme (espèces, virement)
     * @description Réservé à celui qui peut agir sur le bien (propriétaire sans mandat actif, ou gestionnaire mandaté). Crée directement un paiement PAID — pas d'étape de confirmation.
     */
    post: operations["PaymentsController_createManual"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/payments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Historique paginé des paiements, filtrable */
    get: operations["PaymentsController_findAll"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/payments/{id}/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Confirme une déclaration de paiement locataire — passe à PAID */
    post: operations["PaymentsController_confirm"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/payments/{id}/reject": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rejette une déclaration de paiement locataire — motif obligatoire */
    post: operations["PaymentsController_reject"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/payments/{id}/receipt.pdf": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Quittance PDF générée à la volée — jamais persistée
     * @description Disponible uniquement pour un paiement PAID.
     */
    get: operations["PaymentsController_downloadReceipt"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/payment-declarations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Déclare avoir payé une échéance — passe en attente de confirmation
     * @description Réservé au locataire connecté, sur son propre bail. Justificatif (`proof`) optionnel.
     */
    post: operations["PaymentDeclarationsController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/payment-declarations/{id}/proof": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retourne une URL signée pour consulter la preuve de paiement */
    get: operations["PaymentDeclarationsController_getProofUrl"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/payment-declarations/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Annule une déclaration tant qu’elle est en attente de confirmation */
    delete: operations["PaymentDeclarationsController_cancel"];
    options?: never;
    head?: never;
    /**
     * Modifie une déclaration tant qu’elle est en attente de confirmation
     * @description Justificatif (`proof`) optionnel — remplace le précédent si fourni.
     */
    patch: operations["PaymentDeclarationsController_update"];
    trace?: never;
  };
  "/admin/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Statistiques globales plateforme (super admin) */
    get: operations["AdminController_getStats"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liste tous les comptes (super admin) */
    get: operations["AdminController_listUsers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/users/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Détail d'un compte (super admin) */
    get: operations["AdminController_getUserDetail"];
    put?: never;
    post?: never;
    /** Supprimer (anonymiser) un compte (super admin) */
    delete: operations["AdminController_deleteUser"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/reviews/{id}/moderate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Masque ou réaffiche un avis signalé (super admin) */
    patch: operations["AdminController_moderateReview"];
    trace?: never;
  };
  "/managers/{id}/reviews": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Laisse un avis sur un gestionnaire — réservé à un propriétaire ayant eu un mandat accepté avec lui */
    post: operations["ManagerReviewsController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/managers/{id}/reviews/{reviewId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Modifie son propre avis — jamais de suppression */
    patch: operations["ManagerReviewsController_update"];
    trace?: never;
  };
  "/public/managers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Annuaire public des gestionnaires, filtrable par ville d’intervention et note minimale
     * @description Aucune authentification requise.
     */
    get: operations["PublicManagersController_findAll"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/public/managers/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Profil détaillé public d’un gestionnaire — portfolio et avis vérifiés */
    get: operations["PublicManagersController_findOne"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/mandates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liste les mandats où l’appelant est propriétaire mandant ou gestionnaire destinataire */
    get: operations["MandatesController_findAll"];
    put?: never;
    /** Propose un mandat de gestion à un gestionnaire pour un ou plusieurs biens */
    post: operations["MandatesController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/mandates/{id}/accept": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Accepte un mandat proposé — réservé au gestionnaire destinataire */
    post: operations["MandatesController_accept"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/mandates/{id}/revoke": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Révoque (ou refuse) un mandat — par le propriétaire ou le gestionnaire */
    post: operations["MandatesController_revoke"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/manager/portfolio": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Biens sous mandat actif du gestionnaire connecté, distincts de ses propres biens */
    get: operations["ManagerController_getPortfolio"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/managers/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrouve le managerId d’un gestionnaire par email ou téléphone exact */
    get: operations["ManagersController_search"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/dashboard/manager/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Synthèse des biens sous mandat actif, répartition par statut, nombre de propriétaires mandants */
    get: operations["DashboardManagerController_getSummary"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/dashboard/manager/revenue": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Encaissements de la période (mois/année), comparaison à la période précédente, ventilation biens propres/sous mandat */
    get: operations["DashboardManagerController_getRevenue"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/dashboard/manager/alerts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Échéances impayées, baux expirant sous 30 jours, déclarations en attente de confirmation */
    get: operations["DashboardManagerController_getAlerts"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/dashboard/manager/owners": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Propriétaires mandants actuels, avec le nombre de biens confiés à chacun */
    get: operations["DashboardManagerController_getOwners"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/dashboard/manager/upcoming-payments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Prochaines échéances à venir, triées par date */
    get: operations["DashboardManagerController_getUpcomingPayments"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/dashboard/manager/properties/{id}/performance": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Taux de recouvrement à temps sur les 6 derniers mois pour un bien donné */
    get: operations["DashboardManagerController_getPropertyPerformance"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/dashboard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Résumé dashboard — KPIs, revenus mensuels, biens et paiements récents */
    get: operations["DashboardController_getSummary"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/contact": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Envoie un message depuis le formulaire de contact public */
    post: operations["ContactController_submit"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    PushSubscriptionKeysDto: {
      p256dh: string;
      auth: string;
    };
    SubscribePushDto: {
      /** @example https://fcm.googleapis.com/fcm/send/abc123 */
      endpoint: string;
      keys: components["schemas"]["PushSubscriptionKeysDto"];
    };
    UnsubscribePushDto: {
      /** @example https://fcm.googleapis.com/fcm/send/abc123 */
      endpoint: string;
    };
    SignupOwnerDto: {
      email: string;
      password: string;
      firstName: string;
      lastName: string;
      /** @example 90330557 */
      phone: string;
      /** @example Lomé */
      city: string;
      /** @example TG */
      residenceCountry: string;
    };
    SignupManagerDto: {
      email: string;
      password: string;
      firstName: string;
      lastName: string;
      /** @example 90330557 */
      phone: string;
      /** @example Lomé */
      city: string;
    };
    InviteTenantDto: {
      propertyId: string;
      email: string;
      /** @example 90330557 */
      phone: string;
      firstName: string;
      lastName: string;
      /** @description Absent = reprend le loyer actuel du bien */
      monthlyRent?: number;
      /** @description Absent = reprend les charges actuelles du bien */
      monthlyCharges?: number;
      /** @enum {string} */
      paymentFrequency: "MONTHLY" | "QUARTERLY" | "BIANNUAL" | "ANNUAL";
      /** @description Date de début du bail (ISO 8601) */
      startDate: string;
      /** @description Absent = bail ouvert, calendrier glissant sur 12 mois */
      endDate?: string;
      securityDeposit: number;
      depositReturnConditions?: string;
      /** @description Jours avant échéance pour le rappel — omis = pas de rappel configuré */
      reminderDaysBefore?: number;
      /** @description Fenêtre (en jours) de l'alerte de retard après échéance — omis = pas d'alerte configurée */
      overdueAlertWindowDays?: number;
    };
    SetTenantPasswordDto: {
      password: string;
    };
    LoginDto: {
      email: string;
      password: string;
    };
    RequestPasswordResetDto: {
      email: string;
    };
    ConfirmPasswordResetDto: {
      email: string;
      /** @example 123456 */
      code: string;
      newPassword: string;
    };
    UpdateProfileDto: {
      firstName?: string;
      lastName?: string;
      /** @description Jours avant échéance pour le rappel de loyer */
      reminderDaysBefore?: number;
      /** @description Jours de grâce avant l'alerte d'impayé */
      overdueGraceDays?: number;
    };
    UpdateNotificationConsentDto: {
      /** @enum {string} */
      consent: "ACCEPTED" | "DECLINED";
    };
    CreatePropertyDto: {
      /** @enum {string} */
      type: "VILLA" | "APARTMENT" | "STUDIO" | "COMMERCIAL";
      address: string;
      neighborhood: string;
      city: string;
      surfaceArea?: number;
      roomsCount?: number;
      monthlyRent: number;
      monthlyCharges?: number;
      description?: string;
    };
    UpdatePropertyDto: {
      /** @enum {string} */
      type?: "VILLA" | "APARTMENT" | "STUDIO" | "COMMERCIAL";
      /** @enum {string} */
      status?: "OCCUPIED" | "VACANT" | "RENOVATION" | "ARCHIVED";
      address?: string;
      neighborhood?: string;
      city?: string;
      surfaceArea?: number;
      roomsCount?: number;
      monthlyRent?: number;
      monthlyCharges?: number;
      description?: string;
    };
    UploadPropertyDocumentDto: {
      /** @enum {string} */
      type: "STATE_OF_PLAY" | "PROPERTY_TITLE" | "INSURANCE" | "OTHER";
    };
    UpgradeSubscriptionDto: {
      /**
       * @description Forfait cible — doit être strictement supérieur au forfait courant
       * @enum {string}
       */
      tier: "STARTER" | "PRO" | "PREMIUM";
    };
    BlockTenantDto: {
      /** @description Justification obligatoire du blocage */
      reason: string;
    };
    TerminateLeaseDto: {
      terminationReason?: string;
    };
    CreateManualPaymentDto: {
      scheduleEntryId: string;
      paidAmount: number;
      /** @description Date effective du paiement (ISO 8601) */
      paidAt: string;
      /** @enum {string} */
      paymentMethod: "CASH" | "BANK_TRANSFER";
      note?: string;
    };
    RejectPaymentDto: {
      /** @description Motif obligatoire — communiqué au locataire */
      rejectionReason: string;
    };
    CreatePaymentDeclarationDto: {
      scheduleEntryId: string;
      declaredAmount: number;
      /** @description Date effective du paiement (ISO 8601) */
      declaredAt: string;
      /** @enum {string} */
      declaredMethod: "CASH" | "BANK_TRANSFER";
      note?: string;
    };
    UpdatePaymentDeclarationDto: {
      declaredAmount?: number;
      /** @description Date effective du paiement (ISO 8601) */
      declaredAt?: string;
      /** @enum {string} */
      declaredMethod?: "CASH" | "BANK_TRANSFER";
      note?: string;
    };
    ModerateReviewDto: {
      /** @description true = masque l’avis de l’annuaire public, false = le réaffiche */
      isHidden: boolean;
    };
    CreateManagerReviewDto: {
      /** @description Note sur 5 étoiles */
      rating: number;
      comment?: string;
    };
    UpdateManagerReviewDto: {
      rating?: number;
      comment?: string;
    };
    CreateMandateDto: {
      /** @description Biens à confier — tous doivent appartenir en propre à l’appelant */
      propertyIds: string[];
      /** @description Identifiant du gestionnaire désigné (jamais par email/téléphone) */
      managerId: string;
      /** @enum {string} */
      feeType: "PERCENTAGE" | "FLAT";
      /** @description Pourcentage (1-100) si PERCENTAGE, montant FCFA entier si FLAT */
      feeValue: number;
      startDate: string;
      endDate?: string;
    };
    PropertySummaryDto: {
      id: string;
      ownerId: string;
      /** @enum {string} */
      type: "VILLA" | "APARTMENT" | "STUDIO" | "COMMERCIAL";
      /** @enum {string} */
      status: "OCCUPIED" | "VACANT" | "RENOVATION" | "ARCHIVED";
      address: string;
      neighborhood: string;
      city: string;
      surfaceArea?: number | null;
      roomsCount?: number | null;
      monthlyRent: number;
      monthlyCharges: number;
      description?: string | null;
      /** Format: date-time */
      archivedAt?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    MandatePartyDto: {
      id: string;
      firstName: string;
      lastName: string;
      email?: string | null;
      phone?: string | null;
    };
    MandateWithPartiesDto: {
      id: string;
      propertyId: string;
      ownerId: string;
      managerId: string;
      /** @enum {string} */
      status: "PENDING" | "ACTIVE" | "REVOKED" | "EXPIRED";
      /** @enum {string} */
      feeType: "PERCENTAGE" | "FLAT";
      feeValue: number;
      /** Format: date-time */
      startDate: string;
      /** Format: date-time */
      endDate?: string | null;
      /** Format: date-time */
      acceptedAt?: string | null;
      /** Format: date-time */
      revokedAt?: string | null;
      revokedReason?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      property: components["schemas"]["PropertySummaryDto"];
      owner: components["schemas"]["MandatePartyDto"];
      manager: components["schemas"]["MandatePartyDto"];
    };
    RevokeMandateDto: {
      reason?: string;
    };
    CreateContactMessageDto: {
      name: string;
      role?: string;
      email: string;
      phone?: string;
      city?: string;
      subject: string;
      message: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  PushController_getVapidPublicKey: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PushController_subscribe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubscribePushDto"];
      };
    };
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PushController_unsubscribe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UnsubscribePushDto"];
      };
    };
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotifyController_getNotifications: {
    parameters: {
      query: {
        limit: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotifyController_getUnreadCount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HealthController_liveness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HealthController_readiness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Health Check is successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example ok */
            status?: string;
            /**
             * @example {
             *       "database": {
             *         "status": "up"
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /** @example {} */
            error?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up"
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
      /** @description The Health Check is not successful */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example error */
            status?: string;
            /**
             * @example {
             *       "database": {
             *         "status": "up"
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect"
             *       }
             *     }
             */
            error?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up"
             *       },
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect"
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
    };
  };
  AuthController_signupOwner: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignupOwnerDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_signupManager: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignupManagerDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_inviteTenant: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InviteTenantDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_signupTenant: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetTenantPasswordDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_requestPasswordReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RequestPasswordResetDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_confirmPasswordReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfirmPasswordResetDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ListingsController_findAll: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        type?: "VILLA" | "APARTMENT" | "STUDIO" | "COMMERCIAL";
        city?: string;
        neighborhood?: string;
        minRent?: number;
        maxRent?: number;
        roomsCount?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ListingsController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProfileController_getProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProfileController_anonymize: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProfileController_updateProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["UpdateProfileDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProfileController_updateNotificationConsent: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateNotificationConsentDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AccountController_getStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ManagerReportsController_preview: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ownerId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PropertiesController_findAll: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        status?: "OCCUPIED" | "VACANT" | "RENOVATION" | "ARCHIVED";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PropertiesController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePropertyDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PropertiesController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PropertiesController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PropertiesController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePropertyDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PropertiesController_addPhotos: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PropertiesController_removePhoto: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        photoId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PropertiesController_listDocuments: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PropertiesController_addDocuments: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["UploadPropertyDocumentDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PropertiesController_removeDocument: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        documentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  SubscriptionsController_getQuota: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  SubscriptionsController_upgrade: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpgradeSubscriptionDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  SubscriptionsController_cancel: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PropertyTenantsController_blockTenant: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        propertyId: string;
        tenantUserId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BlockTenantDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PropertyTenantsController_getHistory: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
      };
      header?: never;
      path: {
        propertyId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TenantsController_listTenants: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TenantsController_getTenant: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tenantUserId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TenantsController_getLeasesHistory: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
      };
      header?: never;
      path: {
        tenantUserId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  LeasesController_terminate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TerminateLeaseDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  LeasesController_getSchedule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PaymentsController_createManual: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["CreateManualPaymentDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PaymentsController_findAll: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        propertyId?: string;
        tenantUserId?: string;
        status?:
          | "PENDING"
          | "PENDING_CONFIRMATION"
          | "PAID"
          | "PARTIAL"
          | "LATE"
          | "OVERDUE"
          | "REJECTED";
        source?: "CASHPAY_API" | "MANUAL_OWNER" | "TENANT_DECLARATION";
        /** @description Filtre paidAt >= from (ISO 8601) */
        from?: string;
        /** @description Filtre paidAt <= to (ISO 8601) */
        to?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PaymentsController_confirm: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PaymentsController_reject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RejectPaymentDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PaymentsController_downloadReceipt: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PaymentDeclarationsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["CreatePaymentDeclarationDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PaymentDeclarationsController_getProofUrl: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PaymentDeclarationsController_cancel: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PaymentDeclarationsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["UpdatePaymentDeclarationDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminController_getStats: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminController_listUsers: {
    parameters: {
      query: {
        role: string;
        search: string;
        page: number;
        limit: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminController_getUserDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminController_deleteUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminController_moderateReview: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ModerateReviewDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ManagerReviewsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateManagerReviewDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ManagerReviewsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        reviewId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateManagerReviewDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PublicManagersController_findAll: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        /** @description Ville d’intervention exacte (ManagerProfile.zonesOfIntervention) */
        zone?: string;
        minRating?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PublicManagersController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MandatesController_findAll: {
    parameters: {
      query?: {
        status?: "PENDING" | "ACTIVE" | "REVOKED" | "EXPIRED";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MandateWithPartiesDto"][];
        };
      };
    };
  };
  MandatesController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateMandateDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MandatesController_accept: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MandatesController_revoke: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RevokeMandateDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ManagerController_getPortfolio: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ManagersController_search: {
    parameters: {
      query?: {
        email?: string;
        phone?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DashboardManagerController_getSummary: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DashboardManagerController_getRevenue: {
    parameters: {
      query?: {
        period?: "MONTH" | "YEAR";
        /** @description 1-12, ignoré si period=YEAR */
        month?: number;
        year?: number;
        /** @description Restreint le volet "biens sous mandat" à ce propriétaire mandant */
        ownerId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DashboardManagerController_getAlerts: {
    parameters: {
      query?: {
        scope?: "MANAGED" | "OWNED" | "ALL";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DashboardManagerController_getOwners: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DashboardManagerController_getUpcomingPayments: {
    parameters: {
      query?: {
        scope?: "MANAGED" | "OWNED" | "ALL";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DashboardManagerController_getPropertyPerformance: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DashboardController_getSummary: {
    parameters: {
      query?: {
        annee?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ContactController_submit: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateContactMessageDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
