// Longueur attendue du numéro national (sans l'indicatif) par code pays ISO.
// Référence : plans de numérotation nationaux (UIT-T). Ajustée en priorité pour
// le Togo et ses voisins ouest-africains, cœur du marché WARAH.
export const PHONE_DIGIT_LENGTHS: Record<string, number> = {
  TG: 8,
  BJ: 8,
  CI: 10,
  GH: 9,
  SN: 9,
  BF: 8,
  ML: 8,
  GN: 9,
  GW: 7,
  GQ: 9,
  NE: 8,
  NG: 10,
  CM: 9,
  TD: 8,
  CF: 8,
  GA: 8,
  CG: 9,
  CD: 9,
  AO: 9,
  ST: 7,
  CV: 7,
  GM: 7,
  MR: 8,
  SL: 8,
  LR: 8,
  MU: 8,
  SC: 7,
  KM: 7,
  MG: 9,
  RW: 9,
  BI: 8,
  TZ: 9,
  KE: 9,
  UG: 9,
  ET: 9,
  SO: 8,
  DJ: 8,
  ER: 7,
  MZ: 9,
  ZM: 9,
  ZW: 9,
  MW: 9,
  BW: 8,
  NA: 9,
  SZ: 8,
  LS: 8,
  ZA: 9,
  EG: 10,
  MA: 9,
  DZ: 9,
  TN: 8,
  LY: 9,
  SD: 9,
  SS: 9,
  FR: 9,
  BE: 9,
  CH: 9,
  DE: 10,
  ES: 9,
  GB: 10,
  IT: 10,
  PT: 9,
  NL: 9,
  LU: 9,
  IE: 9,
  IS: 7,
  FI: 9,
  SE: 9,
  NO: 8,
  DK: 8,
  PL: 9,
  AT: 10,
  CZ: 9,
  SK: 9,
  HU: 9,
  RO: 9,
  BG: 9,
  GR: 10,
  CY: 8,
  MT: 8,
  HR: 9,
  SI: 8,
  BA: 8,
  RS: 9,
  ME: 8,
  XK: 8,
  MK: 8,
  AL: 9,
  UA: 9,
  BY: 9,
  LT: 8,
  LV: 8,
  EE: 8,
  MD: 8,
  AM: 8,
  AD: 6,
  MC: 8,
  SM: 10,
  LI: 7,
  GI: 8,
  RU: 10,
  AE: 9,
  SA: 9,
  QA: 8,
  KW: 8,
  BH: 8,
  OM: 8,
  YE: 9,
  IQ: 10,
  SY: 9,
  LB: 8,
  JO: 9,
  IL: 9,
  PS: 9,
  TR: 10,
  IR: 10,
  AZ: 9,
  GE: 9,
  TJ: 9,
  TM: 8,
  KG: 9,
  UZ: 9,
  KZ: 10,
  AF: 9,
  IN: 10,
  PK: 10,
  BD: 10,
  LK: 9,
  NP: 10,
  BT: 8,
  MV: 7,
  CN: 11,
  JP: 10,
  KR: 10,
  KP: 10,
  TW: 9,
  HK: 8,
  MO: 8,
  MN: 8,
  TH: 9,
  VN: 9,
  KH: 9,
  LA: 10,
  MM: 9,
  MY: 9,
  SG: 8,
  ID: 10,
  PH: 10,
  TL: 8,
  BN: 7,
  AU: 9,
  NZ: 9,
  PG: 8,
  FJ: 7,
  SB: 7,
  VU: 7,
  TO: 7,
  WS: 7,
  KI: 5,
  NR: 7,
  FM: 7,
  MH: 7,
  PW: 7,
  TV: 6,
  BS: 7,
  BB: 7,
  AI: 7,
  AG: 7,
  VI: 7,
  KY: 7,
  BM: 7,
  GD: 7,
  TC: 7,
  MS: 7,
  LC: 7,
  DM: 7,
  VC: 7,
  DO: 7,
  TT: 7,
  KN: 7,
  JM: 7,
  US: 10,
  MX: 10,
  CU: 8,
  HT: 8,
  BZ: 7,
  GT: 8,
  SV: 8,
  HN: 8,
  NI: 8,
  CR: 8,
  PA: 8,
  BR: 11,
  AR: 10,
  CL: 9,
  CO: 10,
  VE: 10,
  PE: 9,
  EC: 9,
  BO: 8,
  PY: 9,
  UY: 8,
  GY: 7,
  SR: 7,
};

export interface PhonePrefix {
  code: string;
  country: string;
  name: string;
  flag: string;
}

export const PHONE_PREFIXES: PhonePrefix[] = [
  { code: "+228", country: "TG", name: "Togo", flag: "🇹🇬" },
  { code: "+229", country: "BJ", name: "Bénin", flag: "🇧🇯" },
  { code: "+225", country: "CI", name: "Côte d'Ivoire", flag: "🇨🇮" },
  { code: "+233", country: "GH", name: "Ghana", flag: "🇬🇭" },
  { code: "+221", country: "SN", name: "Sénégal", flag: "🇸🇳" },
  { code: "+226", country: "BF", name: "Burkina Faso", flag: "🇧🇫" },
  { code: "+223", country: "ML", name: "Mali", flag: "🇲🇱" },
  { code: "+224", country: "GN", name: "Guinée", flag: "🇬🇳" },
  { code: "+245", country: "GW", name: "Guinée-Bissau", flag: "🇬🇼" },
  { code: "+240", country: "GQ", name: "Guinée équatoriale", flag: "🇬🇶" },
  { code: "+227", country: "NE", name: "Niger", flag: "🇳🇪" },
  { code: "+234", country: "NG", name: "Nigéria", flag: "🇳🇬" },
  { code: "+237", country: "CM", name: "Cameroun", flag: "🇨🇲" },
  { code: "+235", country: "TD", name: "Tchad", flag: "🇹🇩" },
  { code: "+236", country: "CF", name: "Rép. centrafricaine", flag: "🇨🇫" },
  { code: "+241", country: "GA", name: "Gabon", flag: "🇬🇦" },
  { code: "+242", country: "CG", name: "Congo", flag: "🇨🇬" },
  { code: "+243", country: "CD", name: "RD Congo", flag: "🇨🇩" },
  { code: "+244", country: "AO", name: "Angola", flag: "🇦🇴" },
  { code: "+239", country: "ST", name: "Sao Tomé-et-Príncipe", flag: "🇸🇹" },
  { code: "+238", country: "CV", name: "Cap-Vert", flag: "🇨🇻" },
  { code: "+220", country: "GM", name: "Gambie", flag: "🇬🇲" },
  { code: "+222", country: "MR", name: "Mauritanie", flag: "🇲🇷" },
  { code: "+232", country: "SL", name: "Sierra Leone", flag: "🇸🇱" },
  { code: "+231", country: "LR", name: "Libéria", flag: "🇱🇷" },
  { code: "+230", country: "MU", name: "Maurice", flag: "🇲🇺" },
  { code: "+248", country: "SC", name: "Seychelles", flag: "🇸🇨" },
  { code: "+269", country: "KM", name: "Comores", flag: "🇰🇲" },
  { code: "+261", country: "MG", name: "Madagascar", flag: "🇲🇬" },
  { code: "+250", country: "RW", name: "Rwanda", flag: "🇷🇼" },
  { code: "+257", country: "BI", name: "Burundi", flag: "🇧🇮" },
  { code: "+255", country: "TZ", name: "Tanzanie", flag: "🇹🇿" },
  { code: "+254", country: "KE", name: "Kenya", flag: "🇰🇪" },
  { code: "+256", country: "UG", name: "Ouganda", flag: "🇺🇬" },
  { code: "+251", country: "ET", name: "Éthiopie", flag: "🇪🇹" },
  { code: "+252", country: "SO", name: "Somalie", flag: "🇸🇴" },
  { code: "+253", country: "DJ", name: "Djibouti", flag: "🇩🇯" },
  { code: "+291", country: "ER", name: "Érythrée", flag: "🇪🇷" },
  { code: "+258", country: "MZ", name: "Mozambique", flag: "🇲🇿" },
  { code: "+260", country: "ZM", name: "Zambie", flag: "🇿🇲" },
  { code: "+263", country: "ZW", name: "Zimbabwe", flag: "🇿🇼" },
  { code: "+265", country: "MW", name: "Malawi", flag: "🇲🇼" },
  { code: "+267", country: "BW", name: "Botswana", flag: "🇧🇼" },
  { code: "+264", country: "NA", name: "Namibie", flag: "🇳🇦" },
  { code: "+268", country: "SZ", name: "Eswatini", flag: "🇸🇿" },
  { code: "+266", country: "LS", name: "Lesotho", flag: "🇱🇸" },
  { code: "+27", country: "ZA", name: "Afrique du Sud", flag: "🇿🇦" },
  { code: "+20", country: "EG", name: "Égypte", flag: "🇪🇬" },
  { code: "+212", country: "MA", name: "Maroc", flag: "🇲🇦" },
  { code: "+213", country: "DZ", name: "Algérie", flag: "🇩🇿" },
  { code: "+216", country: "TN", name: "Tunisie", flag: "🇹🇳" },
  { code: "+218", country: "LY", name: "Libye", flag: "🇱🇾" },
  { code: "+249", country: "SD", name: "Soudan", flag: "🇸🇩" },
  { code: "+211", country: "SS", name: "Soudan du Sud", flag: "🇸🇸" },
  { code: "+33", country: "FR", name: "France", flag: "🇫🇷" },
  { code: "+32", country: "BE", name: "Belgique", flag: "🇧🇪" },
  { code: "+41", country: "CH", name: "Suisse", flag: "🇨🇭" },
  { code: "+49", country: "DE", name: "Allemagne", flag: "🇩🇪" },
  { code: "+34", country: "ES", name: "Espagne", flag: "🇪🇸" },
  { code: "+44", country: "GB", name: "Royaume-Uni", flag: "🇬🇧" },
  { code: "+39", country: "IT", name: "Italie", flag: "🇮🇹" },
  { code: "+351", country: "PT", name: "Portugal", flag: "🇵🇹" },
  { code: "+31", country: "NL", name: "Pays-Bas", flag: "🇳🇱" },
  { code: "+352", country: "LU", name: "Luxembourg", flag: "🇱🇺" },
  { code: "+353", country: "IE", name: "Irlande", flag: "🇮🇪" },
  { code: "+354", country: "IS", name: "Islande", flag: "🇮🇸" },
  { code: "+358", country: "FI", name: "Finlande", flag: "🇫🇮" },
  { code: "+46", country: "SE", name: "Suède", flag: "🇸🇪" },
  { code: "+47", country: "NO", name: "Norvège", flag: "🇳🇴" },
  { code: "+45", country: "DK", name: "Danemark", flag: "🇩🇰" },
  { code: "+48", country: "PL", name: "Pologne", flag: "🇵🇱" },
  { code: "+43", country: "AT", name: "Autriche", flag: "🇦🇹" },
  { code: "+420", country: "CZ", name: "Tchéquie", flag: "🇨🇿" },
  { code: "+421", country: "SK", name: "Slovaquie", flag: "🇸🇰" },
  { code: "+36", country: "HU", name: "Hongrie", flag: "🇭🇺" },
  { code: "+40", country: "RO", name: "Roumanie", flag: "🇷🇴" },
  { code: "+359", country: "BG", name: "Bulgarie", flag: "🇧🇬" },
  { code: "+30", country: "GR", name: "Grèce", flag: "🇬🇷" },
  { code: "+357", country: "CY", name: "Chypre", flag: "🇨🇾" },
  { code: "+356", country: "MT", name: "Malte", flag: "🇲🇹" },
  { code: "+385", country: "HR", name: "Croatie", flag: "🇭🇷" },
  { code: "+386", country: "SI", name: "Slovénie", flag: "🇸🇮" },
  { code: "+387", country: "BA", name: "Bosnie-Herzégovine", flag: "🇧🇦" },
  { code: "+381", country: "RS", name: "Serbie", flag: "🇷🇸" },
  { code: "+382", country: "ME", name: "Monténégro", flag: "🇲🇪" },
  { code: "+383", country: "XK", name: "Kosovo", flag: "🇽🇰" },
  { code: "+389", country: "MK", name: "Macédoine du Nord", flag: "🇲🇰" },
  { code: "+355", country: "AL", name: "Albanie", flag: "🇦🇱" },
  { code: "+380", country: "UA", name: "Ukraine", flag: "🇺🇦" },
  { code: "+375", country: "BY", name: "Biélorussie", flag: "🇧🇾" },
  { code: "+370", country: "LT", name: "Lituanie", flag: "🇱🇹" },
  { code: "+371", country: "LV", name: "Lettonie", flag: "🇱🇻" },
  { code: "+372", country: "EE", name: "Estonie", flag: "🇪🇪" },
  { code: "+373", country: "MD", name: "Moldavie", flag: "🇲🇩" },
  { code: "+374", country: "AM", name: "Arménie", flag: "🇦🇲" },
  { code: "+376", country: "AD", name: "Andorre", flag: "🇦🇩" },
  { code: "+377", country: "MC", name: "Monaco", flag: "🇲🇨" },
  { code: "+378", country: "SM", name: "Saint-Marin", flag: "🇸🇲" },
  { code: "+423", country: "LI", name: "Liechtenstein", flag: "🇱🇮" },
  { code: "+350", country: "GI", name: "Gibraltar", flag: "🇬🇮" },
  { code: "+7", country: "RU", name: "Russie", flag: "🇷🇺" },
  { code: "+971", country: "AE", name: "Émirats arabes unis", flag: "🇦🇪" },
  { code: "+966", country: "SA", name: "Arabie Saoudite", flag: "🇸🇦" },
  { code: "+974", country: "QA", name: "Qatar", flag: "🇶🇦" },
  { code: "+965", country: "KW", name: "Koweït", flag: "🇰🇼" },
  { code: "+973", country: "BH", name: "Bahreïn", flag: "🇧🇭" },
  { code: "+968", country: "OM", name: "Oman", flag: "🇴🇲" },
  { code: "+967", country: "YE", name: "Yémen", flag: "🇾🇪" },
  { code: "+964", country: "IQ", name: "Irak", flag: "🇮🇶" },
  { code: "+963", country: "SY", name: "Syrie", flag: "🇸🇾" },
  { code: "+961", country: "LB", name: "Liban", flag: "🇱🇧" },
  { code: "+962", country: "JO", name: "Jordanie", flag: "🇯🇴" },
  { code: "+972", country: "IL", name: "Israël", flag: "🇮🇱" },
  { code: "+970", country: "PS", name: "Palestine", flag: "🇵🇸" },
  { code: "+90", country: "TR", name: "Turquie", flag: "🇹🇷" },
  { code: "+98", country: "IR", name: "Iran", flag: "🇮🇷" },
  { code: "+994", country: "AZ", name: "Azerbaïdjan", flag: "🇦🇿" },
  { code: "+995", country: "GE", name: "Géorgie", flag: "🇬🇪" },
  { code: "+992", country: "TJ", name: "Tadjikistan", flag: "🇹🇯" },
  { code: "+993", country: "TM", name: "Turkménistan", flag: "🇹🇲" },
  { code: "+996", country: "KG", name: "Kirghizistan", flag: "🇰🇬" },
  { code: "+998", country: "UZ", name: "Ouzbékistan", flag: "🇺🇿" },
  { code: "+76", country: "KZ", name: "Kazakhstan", flag: "🇰🇿" },
  { code: "+93", country: "AF", name: "Afghanistan", flag: "🇦🇫" },
  { code: "+91", country: "IN", name: "Inde", flag: "🇮🇳" },
  { code: "+92", country: "PK", name: "Pakistan", flag: "🇵🇰" },
  { code: "+880", country: "BD", name: "Bangladesh", flag: "🇧🇩" },
  { code: "+94", country: "LK", name: "Sri Lanka", flag: "🇱🇰" },
  { code: "+977", country: "NP", name: "Népal", flag: "🇳🇵" },
  { code: "+975", country: "BT", name: "Bhoutan", flag: "🇧🇹" },
  { code: "+960", country: "MV", name: "Maldives", flag: "🇲🇻" },
  { code: "+86", country: "CN", name: "Chine", flag: "🇨🇳" },
  { code: "+81", country: "JP", name: "Japon", flag: "🇯🇵" },
  { code: "+82", country: "KR", name: "Corée du Sud", flag: "🇰🇷" },
  { code: "+850", country: "KP", name: "Corée du Nord", flag: "🇰🇵" },
  { code: "+886", country: "TW", name: "Taïwan", flag: "🇹🇼" },
  { code: "+852", country: "HK", name: "Hong Kong", flag: "🇭🇰" },
  { code: "+853", country: "MO", name: "Macao", flag: "🇲🇴" },
  { code: "+976", country: "MN", name: "Mongolie", flag: "🇲🇳" },
  { code: "+66", country: "TH", name: "Thaïlande", flag: "🇹🇭" },
  { code: "+84", country: "VN", name: "Viêt Nam", flag: "🇻🇳" },
  { code: "+855", country: "KH", name: "Cambodge", flag: "🇰🇭" },
  { code: "+856", country: "LA", name: "Laos", flag: "🇱🇦" },
  { code: "+95", country: "MM", name: "Myanmar", flag: "🇲🇲" },
  { code: "+60", country: "MY", name: "Malaisie", flag: "🇲🇾" },
  { code: "+65", country: "SG", name: "Singapour", flag: "🇸🇬" },
  { code: "+62", country: "ID", name: "Indonésie", flag: "🇮🇩" },
  { code: "+63", country: "PH", name: "Philippines", flag: "🇵🇭" },
  { code: "+670", country: "TL", name: "Timor-Leste", flag: "🇹🇱" },
  { code: "+673", country: "BN", name: "Brunei", flag: "🇧🇳" },
  { code: "+61", country: "AU", name: "Australie", flag: "🇦🇺" },
  { code: "+64", country: "NZ", name: "Nouvelle-Zélande", flag: "🇳🇿" },
  { code: "+675", country: "PG", name: "Papouasie-Nvle-Guinée", flag: "🇵🇬" },
  { code: "+679", country: "FJ", name: "Fidji", flag: "🇫🇯" },
  { code: "+677", country: "SB", name: "Îles Salomon", flag: "🇸🇧" },
  { code: "+678", country: "VU", name: "Vanuatu", flag: "🇻🇺" },
  { code: "+676", country: "TO", name: "Tonga", flag: "🇹🇴" },
  { code: "+685", country: "WS", name: "Samoa", flag: "🇼🇸" },
  { code: "+686", country: "KI", name: "Kiribati", flag: "🇰🇮" },
  { code: "+674", country: "NR", name: "Nauru", flag: "🇳🇷" },
  { code: "+691", country: "FM", name: "Micronésie", flag: "🇫🇲" },
  { code: "+692", country: "MH", name: "Îles Marshall", flag: "🇲🇭" },
  { code: "+680", country: "PW", name: "Palaos", flag: "🇵🇼" },
  { code: "+688", country: "TV", name: "Tuvalu", flag: "🇹🇻" },
  { code: "+1242", country: "BS", name: "Bahamas", flag: "🇧🇸" },
  { code: "+1246", country: "BB", name: "Barbade", flag: "🇧🇧" },
  { code: "+1264", country: "AI", name: "Anguilla", flag: "🇦🇮" },
  { code: "+1268", country: "AG", name: "Antigua-et-Barbuda", flag: "🇦🇬" },
  { code: "+1340", country: "VI", name: "Îles Vierges (US)", flag: "🇻🇮" },
  { code: "+1345", country: "KY", name: "Îles Caïmans", flag: "🇰🇾" },
  { code: "+1441", country: "BM", name: "Bermudes", flag: "🇧🇲" },
  { code: "+1473", country: "GD", name: "Grenade", flag: "🇬🇩" },
  { code: "+1649", country: "TC", name: "Turques-et-Caïques", flag: "🇹🇨" },
  { code: "+1664", country: "MS", name: "Montserrat", flag: "🇲🇸" },
  { code: "+1758", country: "LC", name: "Sainte-Lucie", flag: "🇱🇨" },
  { code: "+1767", country: "DM", name: "Dominique", flag: "🇩🇲" },
  { code: "+1784", country: "VC", name: "Saint-Vincent", flag: "🇻🇨" },
  { code: "+1809", country: "DO", name: "Rép. dominicaine", flag: "🇩🇴" },
  { code: "+1868", country: "TT", name: "Trinité-et-Tobago", flag: "🇹🇹" },
  { code: "+1869", country: "KN", name: "Saint-Kitts-et-Nevis", flag: "🇰🇳" },
  { code: "+1876", country: "JM", name: "Jamaïque", flag: "🇯🇲" },
  { code: "+1", country: "US", name: "États-Unis / Canada", flag: "🇺🇸" },
  { code: "+52", country: "MX", name: "Mexique", flag: "🇲🇽" },
  { code: "+53", country: "CU", name: "Cuba", flag: "🇨🇺" },
  { code: "+509", country: "HT", name: "Haïti", flag: "🇭🇹" },
  { code: "+501", country: "BZ", name: "Belize", flag: "🇧🇿" },
  { code: "+502", country: "GT", name: "Guatemala", flag: "🇬🇹" },
  { code: "+503", country: "SV", name: "El Salvador", flag: "🇸🇻" },
  { code: "+504", country: "HN", name: "Honduras", flag: "🇭🇳" },
  { code: "+505", country: "NI", name: "Nicaragua", flag: "🇳🇮" },
  { code: "+506", country: "CR", name: "Costa Rica", flag: "🇨🇷" },
  { code: "+507", country: "PA", name: "Panama", flag: "🇵🇦" },
  { code: "+55", country: "BR", name: "Brésil", flag: "🇧🇷" },
  { code: "+54", country: "AR", name: "Argentine", flag: "🇦🇷" },
  { code: "+56", country: "CL", name: "Chili", flag: "🇨🇱" },
  { code: "+57", country: "CO", name: "Colombie", flag: "🇨🇴" },
  { code: "+58", country: "VE", name: "Venezuela", flag: "🇻🇪" },
  { code: "+51", country: "PE", name: "Pérou", flag: "🇵🇪" },
  { code: "+593", country: "EC", name: "Équateur", flag: "🇪🇨" },
  { code: "+591", country: "BO", name: "Bolivie", flag: "🇧🇴" },
  { code: "+595", country: "PY", name: "Paraguay", flag: "🇵🇾" },
  { code: "+598", country: "UY", name: "Uruguay", flag: "🇺🇾" },
  { code: "+592", country: "GY", name: "Guyana", flag: "🇬🇾" },
  { code: "+597", country: "SR", name: "Suriname", flag: "🇸🇷" },
];

export const PHONE_PREFIXES_SORTED_BY_LENGTH = [...PHONE_PREFIXES].sort(
  (a, b) => b.code.length - a.code.length,
);

export function matchPrefix(raw: string): PhonePrefix | null {
  return (
    PHONE_PREFIXES_SORTED_BY_LENGTH.find((p) => raw.startsWith(p.code)) ?? null
  );
}

export function phoneLengthError(
  raw: string,
): { expected: number; actual: number; country: string } | null {
  const trimmed = raw.trim();
  if (!trimmed) return null;
  const match = matchPrefix(trimmed);
  if (!match) return null;
  const localDigits = trimmed.slice(match.code.length).replace(/\D/g, "");
  const expected = PHONE_DIGIT_LENGTHS[match.country] ?? 8;
  if (localDigits.length !== expected) {
    return { expected, actual: localDigits.length, country: match.name };
  }
  return null;
}

export function phoneIsValid(raw: string): boolean {
  const trimmed = raw.trim();
  if (!trimmed) return false;
  const match = matchPrefix(trimmed);
  if (!match) return /^\+?\d{7,15}$/.test(trimmed);
  return phoneLengthError(trimmed) === null;
}
